version: '3'

services:
  backend:
    build:
      context: ./app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"

pgdb:
  image: postgres
  container_name: pgdb
  environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=12345
  
  volumes:
    - pgdata:/var/lib/postgres/data

  frontend:
    build:
      context: ./frontend
    volumes:
      - react_build:/frontend/build
  
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/frontend
    depends_on:
      - backend
      - frontend

volumes:
  react_build:
  pgdata: